import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'

/**
 * POST /api/orders/[id]/reorder
 * Clone an existing order into a new draft order with the same items.
 * The customer can then update the design and re-checkout.
 */
export async function POST(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const admin = createAdminClient()

  // Load original order — ensure it belongs to this user
  const { data: original, error: orderError } = await admin
    .from('orders')
    .select('*, order_items(*)')
    .eq('id', id)
    .eq('user_id', user.id)
    .single()

  if (orderError || !original) {
    return NextResponse.json({ error: 'Order not found' }, { status: 404 })
  }

  // Create new draft order
  const { data: newOrder, error: createError } = await admin
    .from('orders')
    .insert({
      user_id: user.id,
      order_number: '',           // auto-generated by DB trigger
      status: 'draft',
      subtotal: original.subtotal,
      tax: original.tax,
      shipping_cost: original.shipping_cost,
      total: original.total,
      shipping_address: original.shipping_address,
      billing_address: original.billing_address,
      notes: `Reorder of ${original.order_number}`,
    })
    .select()
    .single()

  if (createError || !newOrder) {
    return NextResponse.json({ error: createError?.message ?? 'Failed to create order' }, { status: 500 })
  }

  // Clone order items — reset status, keep design reference
  const items = (original.order_items ?? []) as Array<{
    product_group_id: string | null
    product_template_id: string | null
    quantity: number
    unit_price: number
    line_total: number
    selected_params: Record<string, unknown>
    design_id: string | null
  }>

  if (items.length > 0) {
    const newItems = items.map((item) => ({
      order_id: newOrder.id,
      product_group_id: item.product_group_id,
      product_template_id: item.product_template_id,
      quantity: item.quantity,
      unit_price: item.unit_price,
      line_total: item.line_total,
      selected_params: item.selected_params ?? {},
      design_id: item.design_id,     // keep the original design
      csv_job_id: null,              // do not carry over CSV jobs
      status: 'pending_design',
    }))

    const { error: itemsError } = await admin.from('order_items').insert(newItems)
    if (itemsError) {
      // Clean up the orphaned order
      await admin.from('orders').delete().eq('id', newOrder.id)
      return NextResponse.json({ error: itemsError.message }, { status: 500 })
    }
  }

  return NextResponse.json({ order: newOrder }, { status: 201 })
}
