'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/hooks/useAuth'
import { useCart } from '@/hooks/useCart'
import { createClient } from '@/lib/supabase/client'
import { formatCurrency } from '@/lib/utils/format'
import { SA_PROVINCES, VAT_RATE } from '@/lib/utils/constants'
import { toast } from 'sonner'

export default function CheckoutPage() {
  const router = useRouter()
  const { user } = useAuth()
  const { items, getSubtotal, getTax, getTotal, clearCart } = useCart()
  const [loading, setLoading] = useState(false)
  const [step, setStep] = useState(1)
  const [shipping, setShipping] = useState({
    full_name: '',
    address_line1: '',
    address_line2: '',
    city: '',
    province: '',
    postal_code: '',
    country: 'ZA',
    phone: '',
  })

  // Populate shipping from user profile
  useEffect(() => {
    if (user) {
      setShipping((prev) => ({
        ...prev,
        full_name: user.full_name || '',
        address_line1: user.address_line1 || '',
        address_line2: user.address_line2 || '',
        city: user.city || '',
        province: user.province || '',
        postal_code: user.postal_code || '',
        phone: user.phone || '',
      }))
    }
  }, [user])

  const handleShippingChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setShipping((prev) => ({ ...prev, [e.target.name]: e.target.value }))
  }

  const handlePlaceOrder = async () => {
    if (!user) {
      toast.error('Please log in to place an order')
      return
    }

    setLoading(true)

    try {
      const supabase = createClient()
      const subtotal = getSubtotal()
      const tax = subtotal * VAT_RATE
      const shippingCost = 0 // Free shipping for now
      const total = subtotal + tax + shippingCost

      // Create order
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          order_number: '', // Auto-generated by trigger
          status: 'pending_payment',
          subtotal,
          tax,
          shipping_cost: shippingCost,
          total,
          shipping_address: shipping,
          billing_address: shipping,
        })
        .select()
        .single()

      if (orderError) throw orderError

      // Create order items
      const orderItems = items.map((item) => ({
        order_id: order.id,
        product_group_id: item.product_group_id,
        product_template_id: item.product_template_id,
        quantity: item.quantity,
        unit_price: item.unit_price,
        line_total: item.line_total,
        selected_params: item.selected_params,
        design_id: item.design_id || null,
        status: 'pending_design' as const,
      }))

      const { error: itemsError } = await supabase.from('order_items').insert(orderItems)
      if (itemsError) throw itemsError

      clearCart()
      toast.success('Order placed successfully!')
      router.push(`/account/orders/${order.id}`)
    } catch (error) {
      toast.error('Failed to place order. Please try again.')
      console.error(error)
    } finally {
      setLoading(false)
    }
  }

  // Redirect to cart if empty
  useEffect(() => {
    if (items.length === 0) {
      router.push('/cart')
    }
  }, [items.length, router])

  if (items.length === 0) {
    return null
  }

  return (
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
      <h1 className="mb-8 text-2xl font-bold text-brand-black">Checkout</h1>

      {/* Steps */}
      <div className="mb-8 flex gap-4">
        {['Shipping', 'Review & Pay'].map((label, i) => (
          <button
            key={label}
            onClick={() => setStep(i + 1)}
            className={`flex items-center gap-2 rounded-full px-4 py-2 text-sm font-medium transition ${
              step === i + 1 ? 'bg-brand-red text-white' : 'bg-gray-100 text-brand-gray-medium'
            }`}
          >
            <span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/20 text-xs">
              {i + 1}
            </span>
            {label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
        <div className="lg:col-span-2">
          {step === 1 && (
            <div className="rounded-lg border border-brand-gray-light bg-white p-6">
              <h2 className="mb-4 text-lg font-semibold text-brand-black">Shipping Address</h2>
              <div className="space-y-4">
                <div>
                  <label className="mb-1 block text-sm font-medium">Full Name *</label>
                  <input name="full_name" value={shipping.full_name} onChange={handleShippingChange} required
                    className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Phone</label>
                  <input name="phone" value={shipping.phone} onChange={handleShippingChange}
                    className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Address Line 1 *</label>
                  <input name="address_line1" value={shipping.address_line1} onChange={handleShippingChange} required
                    className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                </div>
                <div>
                  <label className="mb-1 block text-sm font-medium">Address Line 2</label>
                  <input name="address_line2" value={shipping.address_line2} onChange={handleShippingChange}
                    className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                </div>
                <div className="grid grid-cols-3 gap-4">
                  <div>
                    <label className="mb-1 block text-sm font-medium">City *</label>
                    <input name="city" value={shipping.city} onChange={handleShippingChange} required
                      className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                  </div>
                  <div>
                    <label className="mb-1 block text-sm font-medium">Province *</label>
                    <select name="province" value={shipping.province} onChange={handleShippingChange} required
                      className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none">
                      <option value="">Select...</option>
                      {SA_PROVINCES.map((p) => <option key={p} value={p}>{p}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="mb-1 block text-sm font-medium">Postal Code *</label>
                    <input name="postal_code" value={shipping.postal_code} onChange={handleShippingChange} required
                      className="w-full rounded-lg border border-brand-gray-light px-3 py-2 focus:border-brand-red focus:outline-none" />
                  </div>
                </div>
                <button
                  onClick={() => setStep(2)}
                  className="rounded-lg bg-brand-red px-6 py-2.5 font-medium text-white hover:bg-brand-red-light"
                >
                  Continue to Review
                </button>
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="space-y-6">
              <div className="rounded-lg border border-brand-gray-light bg-white p-6">
                <h2 className="mb-4 text-lg font-semibold text-brand-black">Order Items</h2>
                <div className="space-y-3">
                  {items.map((item) => (
                    <div key={item.id} className="flex justify-between border-b border-gray-100 pb-3 last:border-0">
                      <div>
                        <p className="font-medium">{item.product_name}</p>
                        <p className="text-sm text-brand-gray-medium">Qty: {item.quantity}</p>
                      </div>
                      <p className="font-medium">{formatCurrency(item.line_total)}</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="rounded-lg border border-brand-gray-light bg-white p-6">
                <h2 className="mb-2 text-lg font-semibold text-brand-black">Shipping To</h2>
                <p className="text-sm text-brand-gray-medium">
                  {shipping.full_name}<br />
                  {shipping.address_line1}<br />
                  {shipping.address_line2 && <>{shipping.address_line2}<br /></>}
                  {shipping.city}, {shipping.province} {shipping.postal_code}
                </p>
                <button onClick={() => setStep(1)} className="mt-2 text-sm text-brand-red hover:underline">
                  Edit Address
                </button>
              </div>

              <div className="rounded-lg border-2 border-brand-yellow bg-yellow-50 p-4 text-center">
                <p className="text-sm text-brand-gray">
                  Payment integration coming soon. For now, orders are placed as pending.
                </p>
              </div>

              <button
                onClick={handlePlaceOrder}
                disabled={loading}
                className="w-full rounded-lg bg-brand-red py-3 text-lg font-semibold text-white transition hover:bg-brand-red-light disabled:opacity-50"
              >
                {loading ? 'Placing Order...' : 'Place Order'}
              </button>
            </div>
          )}
        </div>

        {/* Summary Sidebar */}
        <div>
          <div className="sticky top-24 rounded-lg border border-brand-gray-light bg-white p-6">
            <h2 className="mb-4 text-lg font-semibold text-brand-black">Summary</h2>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between"><span className="text-brand-gray-medium">Subtotal</span><span>{formatCurrency(getSubtotal())}</span></div>
              <div className="flex justify-between"><span className="text-brand-gray-medium">VAT (15%)</span><span>{formatCurrency(getTax())}</span></div>
              <div className="flex justify-between"><span className="text-brand-gray-medium">Shipping</span><span>Free</span></div>
              <hr className="border-brand-gray-light" />
              <div className="flex justify-between text-lg font-bold"><span>Total</span><span>{formatCurrency(getTotal())}</span></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
